name: ci

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    uses: ./.github/workflows/reusable-unit-test.yml
    secrets: inherit

  e2e:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: ./.github/workflows/reusable-e2e.yml
    secrets: inherit

  package:
    if: github.event_name == 'push'
    needs:
      - unit-test
      - e2e
    uses: ./.github/workflows/reusable-package.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
