name: reusable-unit-test

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          chmod +x ./run.sh
          ./run.sh unit-test
